-- CREATE INDEXES
-- Q1
CREATE INDEX Q1 ON USER02.YELPBUSINESS (BASE.ISOPEN) INCLUDE(BASE.NAME,BASE.STATE,BASE.STARS);

-- Q2
CREATE INDEX Q2 ON USER02.YELPBUSINESS (BASE.CATEGORIES) INCLUDE(BASE.NAME,BASE.ADDRESS,BASE.CITY,BASE.REVIEWCOUNT);

-- Q3
CREATE INDEX Q3 ON USER02.YELPBUSINESS (ATTRIBUTES.OPEN24HOURS, BASE.ISOPEN, HOURS.MONDAY, HOURS.TUESDAY, HOURS.WEDNESDAY, HOURS.THURSDAY, HOURS.FRIDAY, HOURS.SATURDAY, HOURS.SUNDAY) INCLUDE (BASE.CATEGORIES, BASE.REVIEWCOUNT);

-- Q4
CREATE INDEX Q4 ON USER02.YELPBUSINESS (ATTRIBUTES.SMOKING, HOURS.SUNDAY) INCLUDE(BASE.STATE);

-- Q5
CREATE INDEX Q5 ON USER02.YELPCHECKIN (PERHOUR.CHECKINS) INCLUDE(PERHOUR.WEEKDAY, PERHOUR.HOUR) ASYNC;

-- Q6
CREATE INDEX Q6C ON USER02.YELPCHECKIN (PERHOUR.WEEKDAY, PERHOUR.HOUR) INCLUDE (PERHOUR.CHECKINS) ASYNC;
CREATE INDEX Q6B ON USER02.YELPCHECKIN (BASE.ISOPEN) INCLUDE (BASE.CATEGORIES);

-- Q7
CREATE INDEX Q7C ON USER02.YELPCHECKIN (PERHOUR.WEEKDAY) INCLUDE(PERHOUR.CHECKINS) ASYNC;
CREATE INDEX Q7B ON USER02.YELPBUSINESS (BASE.NAME,BASE.NEIGHBORHOOD,BASE.ADDRESS,BASE.CITY,BASE.STATE,BASE.POSTALCODE,BASE.LATITUDE,BASE.LONGITUDE,BASE.STARS,BASE.REVIEWCOUNT,BASE.ISOPEN,BASE.CATEGORIES);
