-- Query1
SELECT BASE.NAME, BASE.STATE, BASE.STARS
FROM USER02.YELPBUSINESS
WHERE BASE.ISOPEN='1' LIMIT 1000;

-- Query2
SELECT BASE.NAME, BASE.ADDRESS, BASE.CITY, BASE.REVIEWCOUNT
FROM USER02.YELPBUSINESS 
WHERE BASE.CATEGORIES='Drugstores' ORDER BY TO_NUMBER(BASE.REVIEWCOUNT) DESC;

-- Query3
SELECT SUM(TO_NUMBER(BASE.REVIEWCOUNT)) AS REVIEWS, BASE.CATEGORIES
FROM USER02.YELPBUSINESS
WHERE HOURS.MONDAY!='None' AND HOURS.THURSDAY!='None'
AND HOURS.WEDNESDAY!='None' AND HOURS.TUESDAY!='None'
AND HOURS.FRIDAY!='None' AND HOURS.SATURDAY!='None'
AND HOURS.SUNDAY!='None' AND BASE.ISOPEN='1' AND ATTRIBUTES.OPEN24HOURS='True'
GROUP BY BASE.CATEGORIES;

-- Query4
SELECT COUNT(*) AS COMPANIES,BASE.STATE
FROM USER02.YELPBUSINESS
WHERE ATTRIBUTES.SMOKING='False' AND HOURS.SUNDAY!='None'
GROUP BY BASE.STATE;

-- Query5
SELECT PERHOUR.WEEKDAY, PERHOUR.HOUR, SUM(TO_NUMBER(PERHOUR.CHECKINS)) AS CHECKINS
FROM USER02.YELPCHECKIN
WHERE TO_NUMBER(PERHOUR.CHECKINS)>=0 
GROUP BY PERHOUR.WEEKDAY, PERHOUR.HOUR;

-- Query6
SELECT BASE.CATEGORIES AS CATEGORIES, SUM(TO_NUMBER(PERHOUR.CHECKINS)) AS CHECKINS
FROM USER02.YELPCHECKIN AS C
INNER JOIN USER02.YELPBUSINESS AS B
ON B.ROWKEY = C.BUSINESSID
WHERE PERHOUR.WEEKDAY!='Sat' AND PERHOUR.WEEKDAY!='Sun' AND PERHOUR.HOUR BETWEEN '14:00' AND '16:00' AND BASE.ISOPEN = '1'
GROUP BY BASE.CATEGORIES;

-- Query7
SELECT /* INDEX(USER02.YELPBUSINESS Q7B) */ BASE.NAME AS NAME, BASE.NEIGHBORHOOD AS NEIGHBORHOOD, BASE.ADDRESS AS ADDRESS, BASE.CITY AS CITY, BASE.STATE AS STATE, BASE.POSTALCODE AS POSTALCODE, BASE.LATITUDE AS LATITUDE, BASE.LONGITUDE AS LONGITUDE, BASE.STARS AS STARS, BASE.REVIEWCOUNT AS REVIEWCOUNT, BASE.ISOPEN AS ISOPEN, BASE.CATEGORIES AS CATEGORIES, PERHOUR.CHECKINS AS CHECKINS
FROM USER02.YELPCHECKIN AS C
INNER JOIN USER02.YELPBUSINESS AS B
ON B.ROWKEY=C.BUSINESSID
WHERE PERHOUR.WEEKDAY='Sat' ORDER BY TO_NUMBER(PERHOUR.CHECKINS) DESC LIMIT 100;